### PR TITLE
Fixes bug with inview being removed too early

### LINKED ISSUE #32: Inview is removed on inview when it should be removed on completion
This currently stops plugins from plugging into the inview and _isVisible attribute

### PR DESCRIPTION
**Pull request by darylhedley**
fixes #32

### CODE REVIEW

**Comment by dennis-learningpool** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
the way it is written, the event will never be unlistened-to unless component is completed - leading to possible memory leak in IE

**Comment by darylhedley** [comment]
Good spot - I actually found this two days ago, didn't have time to fix it but this should now be removed

**Comment by moloko** [comment]
more credit to @oliverfoster really - he spotted it in this PR: https://github.com/adaptlearning/adapt-contrib-graphic/pull/36
I just noticed this would have the same issue

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Pull request merged**
