### PR TITLE
version bump

### LINKED ISSUE #30: Version and releases are out of sync

### PR DESCRIPTION
**Pull request by darylhedley**
Fixes #30

### CODE REVIEW

**Comment by dancgray** [comment]
+1

**Comment by dennis-learningpool** [comment]
+1

**Comment by taylortom** [comment]
Is this right though? The latest release is 1.1.3

**Comment by dennis-learningpool** [comment]
@taylortom yeah - the new release will need created, or the tag pushed

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
