### PR TITLE
Resolves #944, converted OR to an AND check

### PR DESCRIPTION
**Pull request by brian-learningpool**
This relaxes the rules around setting completion on inview.

### CODE REVIEW

**Comment by moloko** [comment]
personally I'm OK with this, I just wonder if we'd get any push back from course designers that we've relaxed it _too_ much i.e. the user isn't really being required to view all the text any more

**Comment by brian-learningpool** [comment]
That's a possibility.  I'm open to any suggestions here, but I noticed we haven't standardised the completion behaviour for components which don't require interaction.  For example, the Text component's AND was consistent with the Graphic component, but the Assessment Results component uses an OR.

**Comment by moloko** [comment]
convincing enough argument for me
+1

**Comment by chucklorenz** [comment]
I'm for consistency across components. But I think I'm missing the intent here. Are we changing our completion model (inview) in order to fix an intermittent bug? Text components can contain content essential to a course. If a client/designer attaches PLP to a text component, will this OR undermine the natural expectation that the text has been viewed in its entirety?

**Comment by oliverfoster** [comment]
+1 it's an intermittent bug which can be a proper pain to fix and no-one can quite locate properly, i think as long as the component is at least partly onscreen it should be completed - atleast until we find a better solution

**Comment by chucklorenz** [comment]
The proposal is to allow either top or bottom trigger inview (completion). It seems to me that in normal usage we can expect top to be assessed first and satisfy the condition. It will be rare, if ever, that bottom will be tested. Right? Is there justification for having bottom alone trigger inview? Doing so would ensure that the complete component has come into view.

**Comment by oliverfoster** [comment]
there are situations where the bottom won't trigger. which this solves for the time being.

would you prefer if i took some time to fix the issue properly?

**Comment by oliverfoster** [comment]
ok so, i've fixed one of the intermittent issues, i suggest we leave this pr unmerged at the moment and see if  https://github.com/adaptlearning/adapt_framework/pull/956 < fixes it first

then we can change assessmentResults to match the rest rather than changing text and graphic to match assessment results

**Comment by chucklorenz** [comment]
Time zones and my flying around the country hasn’t helped this conversation. Sorry. Ollie, you’ve moved in another direction so the response I was preparing on the plane is a bit out-dated. The gist of my inquiries is to understand the code so that I can represent it to others who are not a part of the discussion. The most natural concern of ID-types is being able to certify the learner has been exposed to the content. With the proposed change, I/we could no longer make a simple statement that PLP completes after the text content has been seen in its entirety. I think this is a fundamental expectation. It would seem that both IDs and plug-ins (Trickle?) would want that kind of clarity. Thanks for looking at alternatives.

**Comment by oliverfoster** [comment]
No worries. It was the core theme stuff that got me there. Seeing the behaviour without styling feels more important now I've experienced it.

I'm hoping that thr above PR might solve this one and I completely agree with you on the your point - it makes much more sense to fix it properly.

**Comment by oliverfoster** [comment]
can ya'll +1 https://github.com/adaptlearning/adapt_framework/pull/956 for me?

**Comment by moloko** [comment]
just revisiting this - partly because I saw this was still open and partly because I just spotted on a project that PR #44 changes the behaviour of inview completion quite a bit... I didn't really spot this at the time due to the syntax of lines 17 - 23, but basically the logic now breaks down like this:
- if there's instruction text set, use that for inview, otherwise:
- if the component has a title, use that for inview, otherwise:
- if the component has body text, use that, otherwise mark as completed immediately

So by that logic, the body text will only be used for inview completion if there's no title or instruction set. 
This seems to be the wrong way round to me - I think it should use body if present, otherwise instruction or title (in that order)

**Comment by moloko** [comment]
alternatively/as well we could allow the author to specify which they'd like via the component.json

**Comment by brian-learningpool** [comment]
@moloko, adding a new property to the JSON might complicate things.

I'm happy enough for the logic to change to `body` > `instruction` > `title` if that works for you?

**Comment by moloko** [comment]
superseded by #50

**Pull request closed without merging**
